name: 'spin trigger pipeline'
description: 'This action sends a POST request to a configured webhook in spinnaker for Dinghy'
author: 'armory-io'
branding:
  icon: 'arrow-right-circle'
  color: 'blue'
inputs:
  baseUrl:
    required: true
    description: 'URL of spinnaker'
  source:
    required: true
    description: 'webhook source to trigger pipeline in spinnaker'
  environment:
    required: true
    description: 'environment to deploy'
  dinghy_host:
    required: true
    description: 'Dinghy hostname'
  lambda_key:
    required: true
    description: 'Lambda key'
  secret:
    required: false
    description: 'secret to allow trigger in spinnaker'
  crtFile:
    required: false
    description: 'client crt file to auth'
  keyFile:
    required: false
    description: 'client key file to auth'
  passphrase:
    required: false
    description: 'passphrase string to auth'
  isEncoded:
    required: false
    description: 'specifies if the cert files needs to be decoded'
outputs:
  eventId:
    description: 'eventId generated by spinnaker'
runs:
  using: 'node12'
  main: 'dist/index.js'
